name: motor_unit_toolbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
      - networkx
      - easydict